name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
        
    - name: Display dotnet version
      run: dotnet --version

    - name: Install dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build

    - name: Run unit tests
      run: dotnet test
  
